import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "attendance",
  title: "Attendance",
  icon: "checkmark-circle-outline",
  order: 7,
  showInTabBar: false,
  enabled: true,
  route: "/(tabs)/attendance",
};
