import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "transcript",
  title: "Transcript",
  icon: "document-text-outline",
  order: 5,
  showInTabBar: false,
  enabled: true,
  route: "/(tabs)/transcript",
};
