import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "exams",
  title: "Exams",
  icon: "create-outline",
  order: 6,
  showInTabBar: false,
  enabled: false,
  route: "/(tabs)/exams",
};
