import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "flappy",
  title: "Flappy",
  icon: "game-controller-outline",
  order: 10,
  showInTabBar: false,
  enabled: false,
  route: "/(tabs)/flappy",
};
