import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "grades",
  title: "Grades",
  icon: "school-outline",
  order: 2,
  showInTabBar: true,
  enabled: false,
  route: "/(tabs)/grades",
};
