/**
 * Track A (Portal) native config plugins — schedule, grades, transcript, cms,
 * exams, attendance, staff, evaluations, and core/portal. Add entries here (not
 * to plugins.shared.js) when portal work needs native config.
 */
/* global __dirname, Buffer -- runs in Node at prebuild, not in the app bundle */
const crypto = require("crypto");
const fs = require("fs");
const path = require("path");
const { AndroidConfig, withAndroidManifest, withDangerousMod } = require("expo/config-plugins");

// ---------------------------------------------------------------------------
// Android trust anchor for student.guc.edu.eg (ADR A-001, "Prerequisite: the
// incomplete certificate chain").
//
// student.guc.edu.eg serves only its leaf certificate and omits the Sectigo
// intermediate. Browsers and Apple's stack fetch the missing intermediate
// themselves; Android doesn't, so every Android device fails that host.
// This adds EXACTLY that one public intermediate as an extra trust anchor for
// EXACTLY that one host, alongside the system store. It is not "trust anything":
// the leaf must still chain to this intermediate by signature, match the
// hostname, and be in date. Cleartext stays off (except for Metro in debug
// builds, which is today's default). No user CAs, no debug-overrides.
// ---------------------------------------------------------------------------

const TRUST_ANCHOR_HOST = "student.guc.edu.eg";
// .crt, not .pem: the repo's .gitignore ignores *.pem (a guard against committing
// private keys), which silently dropped this public certificate from the commit.
const CERT_SOURCE = path.join(
  __dirname,
  "..",
  "src/core/portal/certs/sectigo-public-server-authentication-ca-dv-r36.crt",
);
// SHA-256 of the certificate's DER bytes. Verified against Sectigo's published
// file and against the chain mail.guc.edu.eg serves (see ADR A-001). The build
// fails if the file ever stops matching, so it can't be swapped silently.
const EXPECTED_SHA256 = "8C54C334B66BA4E426772AF4A3F9136C19A1AEC729FDB28C535C07A5A4EF22E0";
const RAW_NAME = "guc_sectigo_dv_r36";
const XML_NAME = "network_security_config";

function sha256OfPem(pem) {
  const body = pem.replace(/-----(BEGIN|END) CERTIFICATE-----/g, "").replace(/\s+/g, "");
  return crypto.createHash("sha256").update(Buffer.from(body, "base64")).digest("hex").toUpperCase();
}

function readVerifiedCert(file = CERT_SOURCE) {
  const pem = fs.readFileSync(file, "utf8");
  if ((pem.match(/BEGIN CERTIFICATE/g) || []).length !== 1) {
    throw new Error(`${file} must contain exactly one certificate.`);
  }
  const actual = sha256OfPem(pem);
  if (actual !== EXPECTED_SHA256) {
    throw new Error(
      `${file} SHA-256 is ${actual}, expected ${EXPECTED_SHA256}. Refusing to trust an unverified certificate.`,
    );
  }
  return pem;
}

/** @param {{ debug: boolean }} opts debug builds keep cleartext for Metro, as they do today. */
function networkSecurityConfigXml({ debug }) {
  return [
    '<?xml version="1.0" encoding="utf-8"?>',
    "<!-- Generated by config/plugins.portal.js (ADR A-001). Don't edit android/ by hand. -->",
    "<network-security-config>",
    `  <base-config cleartextTrafficPermitted="${debug ? "true" : "false"}">`,
    "    <trust-anchors>",
    '      <certificates src="system" />',
    "    </trust-anchors>",
    "  </base-config>",
    '  <domain-config cleartextTrafficPermitted="false">',
    `    <domain includeSubdomains="false">${TRUST_ANCHOR_HOST}</domain>`,
    "    <trust-anchors>",
    '      <certificates src="system" />',
    `      <certificates src="@raw/${RAW_NAME}" />`,
    "    </trust-anchors>",
    "  </domain-config>",
    "</network-security-config>",
    "",
  ].join("\n");
}

function withGucTrustAnchor(config) {
  config = withAndroidManifest(config, (cfg) => {
    const app = AndroidConfig.Manifest.getMainApplicationOrThrow(cfg.modResults);
    app.$["android:networkSecurityConfig"] = `@xml/${XML_NAME}`;
    return cfg;
  });

  return withDangerousMod(config, [
    "android",
    (cfg) => {
      const pem = readVerifiedCert();
      const srcDir = path.join(cfg.modRequest.platformProjectRoot, "app/src");
      const write = (rel, contents) => {
        const file = path.join(srcDir, rel);
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, contents);
      };
      write(`main/res/raw/${RAW_NAME}.pem`, pem);
      write(`main/res/xml/${XML_NAME}.xml`, networkSecurityConfigXml({ debug: false }));
      // Build-type resource overlays: only debug variants may reach Metro over http.
      for (const variant of ["debug", "debugOptimized"]) {
        write(`${variant}/res/xml/${XML_NAME}.xml`, networkSecurityConfigXml({ debug: true }));
      }
      return cfg;
    },
  ]);
}

const plugins = [withGucTrustAnchor];

// Not plugins: exposed only so the tests can check them. app.config.ts spreads
// the array, which copies elements only.
module.exports = Object.assign(plugins, {
  _internals: { networkSecurityConfigXml, readVerifiedCert, sha256OfPem, EXPECTED_SHA256, TRUST_ANCHOR_HOST },
});
