import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "staff",
  title: "Staff",
  icon: "people-outline",
  order: 8,
  showInTabBar: false,
  enabled: true,
  route: "/(tabs)/staff",
};
