import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "cms",
  title: "CMS",
  icon: "folder-outline",
  order: 4,
  showInTabBar: true,
  enabled: false,
  route: "/(tabs)/cms",
};
