#!/usr/bin/env node
/**
 * pnpm gen:feature <name> — copies src/features/_template into src/features/<name>,
 * renaming identifiers, and prints the one route file you still need to add under
 * app/ by hand (the only shared-folder touch a new feature ever needs).
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const TEMPLATE_DIR = path.join(ROOT, "src/features/_template");

function toPascalCase(name) {
  return name.replace(/(^|-)([a-z])/g, (_, __, letter) => letter.toUpperCase());
}

function toCamelCase(name) {
  const pascal = toPascalCase(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

function copyAndRewrite(src, dest, replacements) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destName = entry.name
      .replace(/_template/g, replacements.kebab)
      .replace(/Template/g, replacements.pascal);
    const destPath = path.join(dest, destName);

    if (entry.isDirectory()) {
      copyAndRewrite(srcPath, destPath, replacements);
      continue;
    }

    let content = fs.readFileSync(srcPath, "utf8");
    content = content
      .replace(/_template/g, replacements.kebab)
      .replace(/Template/g, replacements.pascal)
      // "templateItemSchema"-style identifiers need camelCase, not kebab-case
      // (a hyphen isn't a legal identifier character) — must run before the
      // word-boundary replace below, which handles kebab-appropriate prose
      // and CSS-class-like tokens such as ".template-item".
      .replace(/template(?=[A-Z])/g, replacements.camel)
      .replace(/\btemplate\b/g, replacements.kebab);

    if (destName === "manifest.ts") {
      content = content.replace(
        /\/\/ Copy this whole[\s\S]*?once the feature has real screens\.\n/,
        `// Generated by \`pnpm gen:feature\`. Flip \`enabled\` once this feature has real screens.\n`,
      );
    }

    fs.writeFileSync(destPath, content);
  }
}

function main() {
  const name = process.argv[2];
  if (!name || !/^[a-z][a-z0-9-]*$/.test(name)) {
    console.error("Usage: pnpm gen:feature <kebab-case-name>");
    process.exit(1);
  }

  const destDir = path.join(ROOT, "src/features", name);
  if (fs.existsSync(destDir)) {
    console.error(`src/features/${name} already exists.`);
    process.exit(1);
  }

  copyAndRewrite(TEMPLATE_DIR, destDir, {
    kebab: name,
    pascal: toPascalCase(name),
    camel: toCamelCase(name),
  });

  const fixturesDir = path.join(ROOT, "fixtures", name, "raw");
  fs.mkdirSync(fixturesDir, { recursive: true });
  fs.mkdirSync(path.join(ROOT, "fixtures", name, "raw.local"), { recursive: true });
  const fixtureContent = fs
    .readFileSync(path.join(ROOT, "fixtures/_template/raw/list.html"), "utf8")
    .replace(/template/g, name);
  fs.writeFileSync(path.join(fixturesDir, "list.html"), fixtureContent);

  console.log(`Created src/features/${name}/ and fixtures/${name}/.`);
  console.log("Next steps:");
  console.log(`  1. Add app/(tabs)/${name}.tsx re-exporting the new screen.`);
  console.log(`  2. Edit src/features/${name}/manifest.ts (id already set to "${name}").`);
  console.log("  3. pnpm gen:registry (or just pnpm start, which runs it for you).");
}

main();
