import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "mail",
  title: "Mail",
  icon: "mail-outline",
  order: 3,
  showInTabBar: true,
  enabled: false,
  route: "/(tabs)/mail",
};
