import type { FeatureManifest } from "../../core/registry/types";

// Generated by `pnpm gen:feature`. Flip `enabled` once this feature has real screens.
export const manifest: FeatureManifest = {
  id: "evaluations",
  title: "Evaluations",
  icon: "star-outline",
  order: 9,
  showInTabBar: false,
  enabled: false,
  route: "/(tabs)/evaluations",
};
